name: Test

on: [push, pull_request]

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run test

  integration:
    strategy:
      fail-fast: false
      matrix:
        couchdb-image: [ 'public.ecr.aws/medic/cht-couchdb:4.3.0', 'couchdb:3.3.3' ]

    name: Integration
    runs-on: ubuntu-22.04
    env:
      COUCHDB_IMAGE: ${{ matrix.couchdb-image }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: echo $(docker-compose -v)
      - run: npm ci
      - run: npm run integration

  basic-usage:
    strategy:
      fail-fast: false
      matrix:
        version: [ '8.x', '16.x', '18.x' ]

    name: Smoke test for older node versions
    runs-on: ubuntu-22.04
    env:
      COUCHDB_IMAGE: 'couchdb:3.3.3'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo $(docker-compose -v)
      - run: npm install
      - run: npm run integration-basic
